### ISSUE TITLE
kiCAD files do not reflect actual MMU2 production board.

### ISSUE THREAD

**Issue by CacikeOtoao** [prusa3d/MM-control-2.0#1]
@ok1hra Production boards of the MMU2 that people are getting are showing re work to the vias (to the upper right of the sheep logo) after manufacturing that are not reflected on the Source files provided here. Keep in mind that these files were made public after the MMU2 was released and corrections as described above had been made to the boards. Please provide updated documentation or comments regarding these changes as good Open Source practice. Providing outdated information to the community is not a good practice since the community depends on these files to replicate the boards and Prusa Research preaches about Open Source.

**Comment by ericclinedinst** [comment]
My level of surprise is absolutely zero.

**Comment by ok1hra** [comment]
@CacikeOtoao thanks for comment. Can you show me this difference? Because revision 0.3 is last production version

**Comment by ericclinedinst** [comment]
@ok1hra  for starters R42, d7, r44 are removed on the boards you're shipping.   Where as the BOM has them in place.

**Comment by ok1hra** [comment]
@CacikeOtoao Yes, this parts not placed. D7 optional if need powered via usb. R42+R44/ R41+R43 selcted output interface - they can not be place at the same time, see in schematics.
Something else?

**Comment by ericclinedinst** [comment]
In some photos it appears that traces have been cut above the sheep on the right side just above his butt.  

Also when will we be getting the bootloader that was spoken about in anot her github thead? You guys said a week ago it would be posted in "days" @ok1hra

**Comment by ok1hra** [comment]
And you can post this photos? Without another argument you claim is false.

I am not manage bootloader, I cant help you. Ask on support desk.
