### ISSUE TITLE
Schematic for rev 0.4 and later?

### ISSUE THREAD

**Issue by Redferne** [prusa3d/MM-control-2.0#16]
Have connected a I2C display to the P7 port, but need an additional IO pin. Problem is that rev 0.3 schematic shows that P7 is a 6 pin connector, but in rev 0.4 and later it is in reality a 5 pin connector. What is connected to pin 5? Is it SCK, D7 or some other pin?

**Comment by ok1hra** [comment]
P7 is 6 pin hole in PCB, but soldered only 5 pin connector. P7.6 not used.
